magnet/contatos/urls.py
from django.conf.urls import patterns, include, url
from .views import contato_simples, contato_fones
from .views import contato_simples_com_modelform
from .views import contato_fones_com_modelform
from .views import lista_contatos, editar_contato

urlpatterns = patterns('',
    url(r'^simples/$', contato_simples, name='form-contato-simples'),
    url(r'^simplesmf/$', contato_simples_com_modelform, name='modelform-contato-simples'),
    url(r'^fones/$', contato_fones, name='form-contato-fones'),
    url(r'^fonesmf/$', contato_fones_com_modelform, name='modelform-contato-fones'),
    url(r'^listar/$', lista_contatos, name='lista-contatos'),
    url(r'^editar/(\d+)/$', editar_contato, name='editar-contato'),
)

magnet/project/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ct/', include('contatos.urls')),
    url(r'^', include('noticiario.urls')),
)

magnet/contatos/models.py
from django.db import models

class Contato(models.Model):
    nome = models.CharField(max_length=128)
    email = models.EmailField(blank=True)

    def __unicode__(self):
        return self.nome

TIPOS_FONE = (
        ('cel','celular'),
        ('com','comercial'),
        ('res','residencial'),
        ('rec','recados'),
    )

class Fone(models.Model):
    contato = models.ForeignKey(Contato)
    tipo = models.CharField(max_length=8, choices= TIPOS_FONE)
    ddd = models.CharField(max_length=8, default='5511')
    numero = models.CharField(max_length=16)

    def __unicode__(self):
        return '(%s) %s' % (self.ddd, self.numero)

magnet/contatos/forms.py
from django import forms

from .models import Contato, Fone, TIPOS_FONE

class ContatoSimples(forms.Form):
    nome = forms.CharField(max_length=128, help_text='Nome completo')
    email = forms.EmailField(help_text='Email principal')

class FoneForm(forms.Form):
    tipo = forms.ChoiceField(choices= TIPOS_FONE)
    ddd = forms.CharField(max_length=8, initial='5511')
    numero = forms.CharField(max_length=16)

class ContatoModelForm(forms.ModelForm):
    class Meta:
        model = Contato

class FoneModelForm(forms.ModelForm):
    class Meta:
        model = Fone

magnet/contatos/views.py
# coding: utf-8

from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.forms.formsets import formset_factory
from django.forms.models import inlineformset_factory, modelformset_factory
from django.core.urlresolvers import reverse


from .forms import ContatoSimples, FoneForm, ContatoModelForm, FoneModelForm
from .models import Contato, Fone


def contato_simples(request):
    if request.method == 'POST':
        form = ContatoSimples(request.POST)
        if form.is_valid():
            contato = Contato(nome=form.cleaned_data['nome'], email=form.cleaned_data['email'])
            contato.save()
            return render(request, 'contatos/contato_ok.html', {'form':form})
    else: 
        form = ContatoSimples()
    
    return render(request, 'contatos/contato_simples.html', {
        'form': form,
    })

def contato_simples_com_modelform(request):
    if request.method == 'POST':
        form = ContatoModelForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'contatos/contato_ok.html', {'form':form})
    else: 
        form = ContatoSimples()
    
    return render(request, 'contatos/contato_simples.html', {
        'form': form,
    })


def contato_fones(request):
    FonesFormSet = formset_factory(FoneForm)
    if request.method == 'POST':
        form_contato = ContatoSimples(request.POST)
        forms_fones = FonesFormSet(request.POST)
        
        if form_contato.is_valid() and forms_fones.is_valid():
            contato = Contato(nome=form_contato.cleaned_data['nome'], email=form_contato.cleaned_data['email'])
            contato.save()
            for form_fone in forms_fones:
                fone = Fone(contato=contato, 
                            tipo=form_fone.cleaned_data['tipo'],
                            ddd=form_fone.cleaned_data['ddd'],
                            numero=form_fone.cleaned_data['numero'])
                fone.save() 
            
            return render(request, 'contatos/contato_ok.html', {'form_contato': form_contato, 'forms_fones': forms_fones})
    else: 
        form_contato = ContatoSimples()
        forms_fones = FonesFormSet()
    
    return render(request, 'contatos/contato_fones.html', {
        'form_contato': form_contato, 'forms_fones': forms_fones})


def contato_fones_com_modelform(request):
    FonesFormSet = modelformset_factory(Contato, Fone)
    if request.method == 'POST':
        form_contato = ContatoModelForm(request.POST)        
        if form_contato.is_valid():
            contato = form_contato.save()            
            forms_fones = FonesFormSet(request.POST, instance=contato)
            if forms_fones.is_valid():
                forms_fones.save() 
            
            return render(request, 'contatos/contato_ok.html', {'form_contato': form_contato, 'forms_fones': forms_fones})
        else: 
            forms_fones = FonesFormSet(request.POST)

    else: 
        form_contato = ContatoModelForm()
        forms_fones = FonesFormSet()
    
    return render(request, 'contatos/contato_fones.html', {
        'form_contato': form_contato, 'forms_fones': forms_fones})


def lista_contatos(request):
    contatos = Contato.objects.all()
    return render(request, 'contatos/listagem.html', {'contatos':contatos})


def editar_contato(request, id_contato):
    contato = Contato.objects.get(pk=id_contato)
    contato = get_object_or_404(Contato, pk= 1)

    FonesFormSet = inlineformset_factory(Contato, Fone)
    if request.method == "POST":
        form_contato = ContatoModelForm(request.POST, instance=contato)
        forms_fones = FonesFormSet(request.POST, instance= contato)
        if form_contato.is_valid():
            form_contato.save()
        if forms_fones.is_valid():
            forms_fones.save()

            # Do something. Should generally end with a redirect. For example:
            return HttpResponseRedirect(reverse('lista-contatos'))            

    else:
        form_contato = ContatoModelForm(instance=contato)
        forms_fones = FonesFormSet(instance=contato)
    return render(request, "contatos/contato_editar.html",
        {'form_contato': form_contato, 'forms_fones': forms_fones})

magnet/contatos/templates/contatos/contato_editar.html
{%extends "noticiario/fluid.html" %}
{% load bootstrap_toolkit %}

{% block conteudo %}

    <h1>Cadastro de Contato</h1>

    <form method="post" action="." class="form">

    {% csrf_token %}

    {{ form_contato|as_bootstrap }}

    <div id="forms_fones">
        {{ forms_fones.management_form }}

        {% for form_fone in forms_fones %}    
            <div class="form_fone">
                {{ form_fone|as_bootstrap }}
            </div>
        {% endfor %}
    </div>

        <div class="actions">
            <button type="submit" class="btn btn-primary">Enviar</button>
        </div>

    </form>

{% endblock conteudo %}

magnet/contatos/templates/contatos/contato_fones.html
{%extends "noticiario/fluid.html" %}
{% load bootstrap_toolkit %}

{% block conteudo %}

    <h1>Cadastro de Contato</h1>

    <form method="post" action="." class="form">

    {% csrf_token %}

    {{ form_contato|as_bootstrap }}

    <div id="forms_fones">
        {{ forms_fones.management_form }}

        {% for form_fone in forms_fones %}    
            <div class="form_fone">
                {{ form_fone|as_bootstrap }}
            </div>
        {% endfor %}
    </div>

        <div class="actions">
            <button id="ad-fone" type="button" class="btn btn-success">Adicionar Fone</button>
            <button type="submit" class="btn btn-primary">Enviar</button>
        </div>

    <script>
    

    </script>

    </form>

{% endblock conteudo %}
    

magnet/contatos/templates/contatos/contato_ok.html
{%extends "noticiario/fluid.html" %}
{% load bootstrap_toolkit %}

{% block conteudo %}

    <h1>Dados de contato recebidos</h1>

    <br/>

    <table class="table table-bordered">

        {% for campo in form_contato %}
            <tr>
                <th>{{campo.label}}</th>
                <td>{{campo.value}}</td>
            </tr>
        {% endfor %}

    </table>

    {% for form_fone in forms_fones %}

    <table class="table table-bordered">

        {% for campo in form_fone %}
            <tr>
                <th>{{campo.label}}</th>
                <td>{{campo.value}}</td>
            </tr>
        {% endfor %}

    </table>

    {% endfor %}

{% endblock conteudo %}

magnet/contatos/templates/contatos/contato_simples.html
{%extends "noticiario/fluid.html" %}
{% load bootstrap_toolkit %}

{% block conteudo %}

    <h1>Fale conosco</h1>

    <form method="post" action="." class="form">
    {% csrf_token %}

    {{form|as_bootstrap}}

    <div class="actions">
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>

    </form>

{% endblock conteudo %}
    

magnet/contatos/templates/contatos/listagem.html
{%extends "noticiario/fluid.html" %}
{% load bootstrap_toolkit %}

{% block conteudo %}

    <h1>Contatos</h1>

    <br/>

    <table class="table table-bordered table-striped">

        {% for contato in contatos %}
            <tr>
                <th>{{contato.nome}}</th>
                <td>
                    {% for fone in contato.fone_set.all %}
                    {{fone}},
                    {% endfor %}
                </td>
                <th><a href="/ct/editar/{{contato.pk}}"><spam class="label label-info">Editar</a></th>
            </tr>
        {% endfor %}

    </table>

{% endblock conteudo %}